### PR TITLE
Allow request data to be a function

### LINKED ISSUE #12: Support a function in data (or even a handler attribute)
It would be nice to support a function as the route data attribute with the request as an argument, so responses could be customized according to the request attributes, and it would allow storing a local state, as in the given example:

```js
const surveyAnswers = {};

const routes = [
  {
    path: '/answers',
    methods: [
      {
        type: 'post',
        data: ({ payload: { surveyId, answers } }) => {
          surveyAnswers[surveyId] = answers;
          return answers;
        },
      },
      {
        type: 'get',
        data: ({ query: { surveyId } }) => {
          return surveyAnswers[surveyId] || [];
        },
      },
    ],
  },
];

export default routes;
```

Don't know if it's overkill (probably it is), but if other response attributes could be changed (like headers), then we could have a handler function argument with `(request, response)` attributes, to customize the response at all.

### PR DESCRIPTION
**Pull request by fsmaia**
Closes #12

### CODE REVIEW

**Comment by nolleto** [comment]
Maybe you could update `MethodProperties` for something like:

```ts
import { Request } from 'express';
import Search from "./Search";

export default interface MethodProperties {
  code?: number,
  data?: string | object | ((req: Request) => any),
  file?: string,
  paginated?: boolean,
  search?: Search,
}
```

This will help the autocomplete:

Screen Shot 2020-04-16 at 11 15 04

**Comment by fsmaia** [comment]
How about `data?: any | ((req: Request) => any)`?

**Comment by nolleto** [comment]
I've tested here and unfortunately, with `any` when you are passing a `Function` to `data` the autocomplete doesn't know what is the parameter type 😢 

Screen Shot 2020-04-16 at 12 06 29

**Comment by fsmaia** [comment]
I'll take a look

**Comment by fsmaia** [comment]
@nolleto, confirmed that inference doesn't work at all, had to give up and revert data type to `any`.

**Pull request merged**
